[package]
name = "SPACEAPE"
license = "MIT"
licence-file = "LICENSE.MIT"
version = "0.1.0"
authors = ["Igor null <m1el.2027@gmail.com>"]

[lib]
crate-type=["cdylib"]

[dependencies]

[dependencies.rand]
version = "0.4.1"
default-features = false
